### ISSUE TITLE
Hola Roman 

### ISSUE THREAD

**Issue by AzadesHB** [sarriaroman/Keystone-Rest-API#2]
Estoy realizando con fin tu ejemplo en una pagina creada con keystone la pagina solo muestra un nombre completo al integarar con el KeystoneRestApi para consultar nombre por webservice  me genera el siguiente error 

 keystone.init(config);
               ^

ReferenceError: config is not defined
    at Object.<anonymous> (/home/eeb2/keystone.js:58:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

en la documentacion no viene que nes este objeto config, me podrias orientar

**Comment by sarriaroman** [comment]
Podrias crear un gist con el JS que usas para inicializar el server? Ahi básicamente indica que te falta el config object.
